package com.example.coupon.service;

import com.example.coupon.entity.Coupon;
import com.example.coupon.exception.CouponException;

import java.util.List;

/**
 * Redis-related operation service interface definitions
 * 1. User's three-state coupon Cache-related operations.
 * 2. Coupon code Cache operation generated by coupon template
*/
public interface IRedisService {

    List<Coupon> getCachedCoupons(Long userId, Integer status);

    void saveEmptyCouponListToCache(Long userId, List<Integer> status);

    String tryToAcquireCouponCodeFromCache(Integer templateId);

    Integer addCouponToCache(Long userId, List<Coupon> coupons,
                             Integer status) throws CouponException;
}
